# Generated by Django 3.1.6 on 2021-09-24 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('finl_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Финальная цена продуктов')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WoshMachin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена продукта')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка продукта')),
                ('description', models.TextField(null=True, verbose_name='Картинка продукта')),
                ('qantity_turnover', models.CharField(max_length=255, verbose_name='Количество оборотов')),
                ('capacity', models.CharField(max_length=255, verbose_name='Емкость')),
                ('qantity_of_modes', models.CharField(max_length=255, verbose_name='Количество режимов')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена продукта')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка продукта')),
                ('description', models.TextField(null=True, verbose_name='Картинка продукта')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('charge_capacity', models.CharField(max_length=255, verbose_name='Емкость батареи')),
                ('data_capacity', models.CharField(max_length=255, verbose_name='Память')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативная память')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('finl_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Финальная цена продукта')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='Firstapp.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Firstapp.customer', verbose_name='Владлец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='related_cart', to='Firstapp.CartProduct', verbose_name='Продукты'),
        ),
    ]
