# Generated by Django 3.1.6 on 2021-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0002_auto_20211103_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='finl_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Финальная цена продуктов'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Финальная цена продукта'),
        ),
    ]
